name: "Statamic Frontend Test"
description: "Install, lint, audit and build frontend"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "24"

  working-directory:
    description: "Directory where package.json is located"
    required: false
    default: "."

runs:
  using: "composite"
  steps:

    - name: 🧾 Checkout Code
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: 🟢 Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: 📦 Install frontend dependencies
      run: |
        set -euo pipefail
        npm ci --prefer-offline --no-audit --no-fund --loglevel=error
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: 🔍 Lint
      run: |
        set -euo pipefail
        npm run lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: 🔐 Security audit
      if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
      run: |
        set -euo pipefail
        npm audit signatures
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: 🏗 Build
      run: |
        set -euo pipefail
        export NODE_ENV=production
        export CI=true
        npm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}