name: "Slack Notify"

description: "Send message to Slack"
inputs:
  webhook_url:
    required: true
  message:
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack message
      shell: bash
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\": \"${{ inputs.message }}\"}" \
        ${{ inputs.webhook_url }}