name: "Statamic Backend Test"
description: "Runs composer install + static analysis for Statamic projects"

inputs:
  php-version:
    description: "PHP version"
    required: false
    default: "8.3"

  composer-auth:
    description: "Composer auth.json content"
    required: true

runs:
  using: "composite"
  steps:

    - name: 🧾 Checkout Code
      uses: actions/checkout@v6

    - name: 🧪 Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: mbstring, xml, ctype

    - name: Cache vendor
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

    - name: Setup COMPOSER_AUTH
      run: |
        mkdir -p ~/.config/composer
        echo '${{ inputs.composer-auth }}' > ~/.config/composer/auth.json
      shell: bash

    - name: 📦 Install Composer Dependencies
      run: |
        composer install \
          --no-interaction \
          --no-progress \
          --prefer-dist \
          --no-scripts \
          --no-autoloader
        composer dump-autoload --optimize --no-scripts
      shell: bash

    - name: Static Analysis
      run: |
        php vendor/bin/phpcs &
        PHPCS_PID=$!
        php vendor/bin/phpstan &
        PHPSTAN_PID=$!
        wait $PHPCS_PID $PHPSTAN_PID
      shell: bash