name: "Statamic Backend Test"
description: "Runs composer install + static analysis for Statamic projects"

inputs:
  php-version:
    description: "PHP version"
    required: false
    default: "8.3"

  composer-auth:
    description: "Composer auth.json content"
    required: true

runs:
  using: "composite"
  steps:

    - name: 🧾 Checkout Code
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: 🧪 Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: mbstring, xml, ctype
        ini-values: |
          memory_limit=-1
          opcache.enable_cli=1
          opcache.jit=0

    - name: Cache composer
      uses: actions/cache@v5
      with:
        path: |
          ~/.composer/cache
          ~/.cache/composer
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
          composer-

    - name: Cache PHPStan
      uses: actions/cache@v5
      with:
        path: tmp/phpstan
        key: ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-phpstan-
          phpstan-

    - name: Setup COMPOSER_AUTH
      run: |
        set -euo pipefail
        mkdir -p ~/.config/composer
        printf "%s" '${{ inputs.composer-auth }}' > ~/.config/composer/auth.json
      shell: bash

    - name: 📦 Install Composer Dependencies
      env:
        COMPOSER_MEMORY_LIMIT: -1
        COMPOSER_MAX_PARALLEL_HTTP: 10
      run: |
        set -euo pipefail

        composer install \
          --no-interaction \
          --no-progress \
          --prefer-dist \
          --no-scripts \
          --no-progress \
          --optimize-autoloader \
          --ansi
      shell: bash

    - name: Static Analysis
      run: |
        set -euo pipefail

        echo "Running PHPCS..."
        vendor/bin/phpcs --parallel=$(nproc)

        echo "Running PHPStan..."
        vendor/bin/phpstan --no-progress --memory-limit=1G
      shell: bash