---
name: Trigger Version & Tagging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create version tag and release
        uses: finetic/deployers/versioning@main
        with:
          github_token: ${{ github.token }}
          git_username: ${{ vars.GIT_USERNAME }}
          git_email: ${{ vars.GIT_EMAIL }}
