---
name: Statamic Addon CI

on:
  workflow_call:

jobs:
  check:
    name: Check Addon Quality (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.3]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-bridge
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pgsql, gd, exif, amqp

      - name: Composer validate
        run: composer validate --strict

      - name: Lint PHP files (php -l)
        run: |
          find . -type f -name "*.php" -exec php -l {} \;

      - name: Check forbidden PHP functions
        run: |
          if grep -R --include="*.php" -E "eval\(|shell_exec\(|exec\(|system\(|passthru\(" .; then
            echo "❌ Forbidden functions detected in PHP files!";
            exit 1;
          else
            echo "✅ Geen verboden functies gevonden.";
          fi

      - name: Composer security audit
        run: composer audit

      - name: PHPUnit tests (optioneel)
        run: ./vendor/bin/phpunit --testdox || echo "⚠️ Geen tests gevonden (geen blokkade voor kleine addons)"
